name: wechat
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.4
  dio: ">=2.1.2 <6.0.0"
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^0.5.2
  url_launcher: ^5.0.2
  flutter_easyrefresh: ^1.2.7
  provide: ^1.0.2
  fluttertoast: ^3.0.4
  fluro: ^1.4.0
  flutter_html: ^0.9.6
  shared_preferences: ^0.5.2
  web_socket_channel: ^1.0.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/ic_file_transfer.png
    - assets/images/ic_fengchao.png
    - assets/images/ic_tx_news.png
    - assets/images/ic_wx_games.png
    - assets/images/ic_new_friend.png
    - assets/images/ic_group_chat.png
    - assets/images/ic_tag.png
    - assets/images/ic_public_account.png
    - assets/images/ic_bottle_msg.png
    - assets/images/ic_feeds.png
    - assets/images/ic_game_entry.png
    - assets/images/ic_mini_program.png
    - assets/images/ic_people_nearby.png
    - assets/images/ic_quick_scan.png
    - assets/images/ic_quick_search.png
    - assets/images/ic_shake_phone.png
    - assets/images/ic_shopping.png
    - assets/images/ic_social_circle.png 
    - assets/images/ic_wallet.png
    - assets/images/ic_album.png
    - assets/images/ic_collections.png
    - assets/images/ic_cards_wallet.png
    - assets/images/ic_emotions.png
    - assets/images/ic_settings.png
    - assets/images/ic_qrcode_preview_tiny.png
    - assets/images/default_nor_avatar.png
    - assets/images/ad_game_notify.png

  fonts:
    - family: wxIconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf 